"""add events table

Revision ID: 33accce6fdba
Revises: 1ae11c76d131
Create Date: 2026-04-30 10:16:44.272985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '33accce6fdba'
down_revision: Union[str, Sequence[str], None] = '1ae11c76d131'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('event_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('endpoint', sa.String(length=100), nullable=False),
    sa.Column('request_id', sa.String(length=32), nullable=False),
    sa.Column('provider_used', sa.String(length=50), nullable=False),
    sa.Column('fallback_used', sa.Boolean(), nullable=False),
    sa.Column('summary', sa.String(length=255), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('event_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('events')
    # ### end Alembic commands ###
