"""add msg to agent_steps

Revision ID: 888376c9b5e1
Revises: 8b11d003a0bc
Create Date: 2026-03-26 10:31:11.881405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '888376c9b5e1'
down_revision: Union[str, Sequence[str], None] = '8b11d003a0bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_steps', sa.Column('msg', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_steps', 'msg')
    # ### end Alembic commands ###
