"""add agent_steps table

Revision ID: 8b11d003a0bc
Revises: 027aef26b80c
Create Date: 2026-03-26 10:27:21.668338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b11d003a0bc'
down_revision: Union[str, Sequence[str], None] = '027aef26b80c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_steps',
    sa.Column('step_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tool_name', sa.String(length=255), nullable=False),
    sa.Column('input_text', sa.String(length=255), nullable=False),
    sa.Column('ok_flag', sa.Boolean(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('step_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agent_steps')
    # ### end Alembic commands ###
